/** Maps SKU part numbers to human-friendly license names. */
export const SKU_FRIENDLY_NAMES: Record<string, string> = {
  AAD_PREMIUM: "Entra ID P1",
  AAD_PREMIUM_P2: "Entra ID P2",
  ADALLOM_STANDALONE: "Microsoft Defender for Cloud Apps",
  ATP_ENTERPRISE: "Microsoft Defender for Office 365 P1",
  BUSINESS_BASIC: "Microsoft 365 Business Basic",
  BUSINESS_PREMIUM: "Microsoft 365 Business Premium",
  BUSINESS_STANDARD: "Microsoft 365 Business Standard",
  DESKLESSPACK: "Office 365 F3",
  EMS: "Enterprise Mobility + Security E3",
  EMSPREMIUM: "Enterprise Mobility + Security E5",
  ENTERPRISEPACK: "Office 365 E3",
  ENTERPRISEPREMIUM: "Office 365 E5",
  ENTERPRISEPREMIUM_NOPSTNCONF: "Office 365 E5 (without Audio Conferencing)",
  EXCHANGEENTERPRISE: "Exchange Online Plan 2",
  EXCHANGESTANDARD: "Exchange Online Plan 1",
  FLOW_FREE: "Power Automate Free",
  IDENTITY_THREAT_PROTECTION: "Microsoft 365 E5 Security",
  INFORMATION_PROTECTION_COMPLIANCE: "Microsoft 365 E5 Compliance",
  INTUNE_A: "Microsoft Intune Plan 1",
  M365_E5_SUITE_COMPONENTS: "Microsoft 365 E5 Suite",
  M365_F1: "Microsoft 365 F1",
  MCOEV: "Microsoft Teams Phone Standard",
  MCOIMP: "Skype for Business Online Plan 1",
  MCOMEETADV: "Microsoft 365 Audio Conferencing",
  MEETING_ROOM: "Microsoft Teams Rooms Standard",
  Microsoft_365_Copilot: "Microsoft 365 Copilot",
  O365_BUSINESS: "Microsoft 365 Apps for Business",
  O365_BUSINESS_ESSENTIALS: "Microsoft 365 Business Basic",
  O365_BUSINESS_PREMIUM: "Microsoft 365 Business Standard",
  OFFICESUBSCRIPTION: "Microsoft 365 Apps for Enterprise",
  POWER_BI_PRO: "Power BI Pro",
  POWER_BI_STANDARD: "Power BI Free",
  POWERAPPS_VIRAL: "Power Apps Trial",
  PROJECTPREMIUM: "Project Online Premium",
  PROJECTPROFESSIONAL: "Project Plan 3",
  RIGHTSMANAGEMENT: "Azure Information Protection P1",
  SMB_APPS: "Microsoft 365 Apps for Business",
  SPB: "Microsoft 365 Business Premium",
  SPE_E3: "Microsoft 365 E3",
  SPE_E5: "Microsoft 365 E5",
  SPE_F1: "Microsoft 365 F3",
  STREAM: "Microsoft Stream Trial",
  TEAMS_EXPLORATORY: "Microsoft Teams Exploratory",
  THREAT_INTELLIGENCE: "Microsoft Defender for Office 365 P2",
  VISIOCLIENT: "Visio Plan 2",
  VISIOONLINE_PLAN1: "Visio Plan 1",
  WIN10_PRO_ENT_SUB: "Windows 10/11 Enterprise E3",
  WIN10_VDA_E5: "Windows 10/11 Enterprise E5",
  WINDOWS_STORE: "Windows Store for Business",
};

export function friendlySkuName(partNumber: string): string {
  return SKU_FRIENDLY_NAMES[partNumber] ?? partNumber;
}
